# Generated by Django 5.0.1 on 2024-02-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
