# Generated by Django 5.0.1 on 2024-02-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_category_news_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='query',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
